<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { Activity, AlertTriangle, ArrowDownToLine, Check, CheckCircle2, ChevronRight, Plus, Search, ShieldAlert } from "lucide-vue-next";

type Entry = { name: string; detail: string; status: string; value: string };
type Setup = { title: string; label: string; description: string; stats: string[]; action: string; records: Entry[] };
const route = useRoute();
const key = computed(() => String(route.meta.tool ?? route.path.split("/")[1] ?? "users"));
const setups: Record<string, Setup> = {
 users:{title:"Users management",label:"CUSTOMER ACCOUNTS",description:"Search customers and review account activity.",stats:["58,920 total users","1,284 joined this month","42 flagged for review"],action:"Export users",records:[{name:"Ali Khan",detail:"ali.khan@example.test · Joined 02 Oct",status:"Active",value:"12 orders"},{name:"Sara Ahmed",detail:"sara.ahmed@example.test · Joined 01 Oct",status:"Active",value:"4 orders"},{name:"Usman Malik",detail:"usman.m@example.test · Joined 28 Sep",status:"Review",value:"2 disputes"}]},
 shipments:{title:"Shipment management",label:"MARKETPLACE LOGISTICS",description:"Review carrier handoffs and delayed deliveries.",stats:["1,422 in transit","38 delayed shipments","96% on-time delivery"],action:"Export shipments",records:[{name:"SHP-48120",detail:"BX-240812-7843 · Karachi hub",status:"In transit",value:"ETA 03 Oct"},{name:"SHP-48086",detail:"BX-240811-1107 · Lahore hub",status:"Delayed",value:"ETA 04 Oct"},{name:"SHP-47930",detail:"BX-240809-0914 · Islamabad hub",status:"Delivered",value:"02 Oct"}]},
 returns:{title:"Returns & refunds",label:"DISPUTE WORKSPACE",description:"Resolve return requests and issue marketplace refunds.",stats:["42 open requests","PKR 286,400 requested","9 overdue"],action:"Export returns",records:[{name:"RET-48201",detail:"Ali Khan · Item arrived damaged",status:"New",value:"PKR 84,999"},{name:"RET-48179",detail:"Sana Ahmed · Wrong variant",status:"Reviewing",value:"PKR 28,999"},{name:"RET-48064",detail:"Hamza R. · Refund pending",status:"Approved",value:"PKR 19,499"}]},
 promotions:{title:"Promotion overview",label:"MARKETPLACE GROWTH",description:"Monitor active merchant offers and campaign impact.",stats:["18 live promotions","PKR 1.2M sales driven","8.7% average discount"],action:"Create promotion",records:[{name:"Autumn Tech Event",detail:"43 sellers · Ends 08 Oct",status:"Active",value:"PKR 640,200"},{name:"Home Refresh",detail:"18 sellers · Starts 06 Oct",status:"Scheduled",value:"PKR 320,100"},{name:"Weekend Flash",detail:"12 sellers · Ends today",status:"Ending soon",value:"PKR 148,800"}]},
 vouchers:{title:"Voucher management",label:"DISCOUNT CODES",description:"Create, activate and review voucher performance.",stats:["26 active codes","8,942 redemptions","PKR 294K discounts"],action:"Create voucher",records:[{name:"BAZAARX10",detail:"10% off · Minimum PKR 10,000",status:"Active",value:"3,412 used"},{name:"WELCOME2000",detail:"PKR 2,000 off · New customers",status:"Active",value:"2,205 used"},{name:"TECHWEEK",detail:"15% off electronics · Expires 08 Oct",status:"Scheduled",value:"842 used"}]},
 "flash-sales":{title:"Flash sales",label:"LIMITED TIME OFFERS",description:"Schedule short promotions and monitor stock readiness.",stats:["4 live sales","68 products featured","12 low-stock items"],action:"Schedule flash sale",records:[{name:"Evening Tech Drop",detail:"Today · 18:00–22:00",status:"Live",value:"31 products"},{name:"Home Essentials",detail:"04 Oct · 12:00–18:00",status:"Scheduled",value:"22 products"},{name:"Weekend Style",detail:"Draft · Setup incomplete",status:"Needs review",value:"15 products"}]},
 campaigns:{title:"Campaign management",label:"MARKETING CALENDAR",description:"Coordinate marketplace-wide seasonal campaigns.",stats:["12 campaigns","PKR 4.8M attributed GMV","6 scheduled"],action:"Create campaign",records:[{name:"BazaarX Mega Days",detail:"01–08 Oct · Electronics & home",status:"Active",value:"PKR 2.4M GMV"},{name:"Back to School",detail:"10–20 Oct · Computing",status:"Scheduled",value:"PKR 1.1M target"},{name:"Seller Spotlight",detail:"Draft · Merchant stories",status:"Planning",value:"8 sellers"}]},
 fraud:{title:"Fraud & risk",label:"TRUST AND SAFETY",description:"Investigate suspicious payments, accounts and merchant activity.",stats:["7 high-risk alerts","3 payment reviews","2 sellers restricted"],action:"Export risk log",records:[{name:"RISK-9821",detail:"Repeated payment failures · Customer review",status:"High risk",value:"PKR 229,999"},{name:"RISK-9813",detail:"Unusual return pattern · Seller review",status:"Investigating",value:"11 requests"},{name:"RISK-9798",detail:"Address mismatch · Payment review",status:"Resolved",value:"PKR 84,999"}]},
 support:{title:"Support tickets",label:"CUSTOMER OPERATIONS",description:"Triage buyer and seller questions from one queue.",stats:["24 open tickets","6 urgent tickets","22 min median first response"],action:"Create ticket",records:[{name:"TKT-9821",detail:"Order not received · Ali Hassan",status:"Urgent",value:"2h ago"},{name:"TKT-9818",detail:"Seller payout status · TechStore",status:"Open",value:"4h ago"},{name:"TKT-9776",detail:"Product quality issue · Sana Ahmed",status:"Waiting",value:"Yesterday"}]},
 analytics:{title:"Marketplace analytics",label:"PLATFORM PERFORMANCE",description:"Review order volume, gross value and marketplace health.",stats:["PKR 12.4M GMV","8,462 orders","320 active sellers"],action:"Export report",records:[{name:"Gross marketplace value",detail:"Compared with previous 30 days",status:"+18%",value:"PKR 12.4M"},{name:"Order completion",detail:"Delivered orders / total orders",status:"72%",value:"6,087 orders"},{name:"Average order value",detail:"After discount, before delivery",status:"+6.2%",value:"PKR 1,466"}]},
 "audit-logs":{title:"Audit logs",label:"ADMIN ACTIVITY",description:"Review important changes performed in the marketplace portal.",stats:["1,284 events this month","8 administrators","0 unreviewed critical events"],action:"Download audit log",records:[{name:"Product approved",detail:"Admin: M. Siddiqui · SKU BX-12884",status:"Completed",value:"10:24 AM"},{name:"Seller application updated",detail:"Admin: H. Noor · TechStore Official",status:"Completed",value:"09:52 AM"},{name:"Voucher activated",detail:"Admin: A. Khan · BAZAARX10",status:"Completed",value:"Yesterday"}]},
 settings:{title:"System settings",label:"PLATFORM CONFIGURATION",description:"Manage marketplace policies and operational defaults.",stats:["All systems operational","PKR currency","Asia/Karachi timezone"],action:"Save settings",records:[{name:"Marketplace commission",detail:"Default seller commission rate",status:"Enabled",value:"8%"},{name:"Buyer returns window",detail:"Days from delivery date",status:"Enabled",value:"7 days"},{name:"Order notification emails",detail:"Buyer and seller order events",status:"Enabled",value:"On"}]},
 };
const page = computed(() => setups[key.value] ?? setups.users);
const rows = ref<Entry[]>([]); const search = ref(""); const feedback = ref("");
const filtered = computed(() => rows.value.filter((row) => `${row.name} ${row.detail} ${row.status}`.toLowerCase().includes(search.value.toLowerCase())));
function load() { rows.value = JSON.parse(localStorage.getItem(`bx-admin-${key.value}`) ?? "null") as Entry[] ?? structuredClone(page.value.records); feedback.value = ""; }
watch(key, load, { immediate: true });
function update(row: Entry) {
  if (key.value === "users") row.status = row.status === "Active" ? "Suspended" : "Active";
  else if (key.value === "settings") row.status = row.status === "Enabled" ? "Paused" : "Enabled";
  else if (key.value === "returns" && row.status === "Approved") row.status = "Refunded";
  else row.status = "Reviewed";
  localStorage.setItem(`bx-admin-${key.value}`, JSON.stringify(rows.value));
  feedback.value = `${row.name} saved as ${row.status}.`;
}
function primaryAction() {
  if (["analytics","audit-logs","users","shipments","returns"].includes(key.value)) {
    const csv = ["Name,Details,Status,Value", ...rows.value.map((row) => `"${row.name}","${row.detail}","${row.status}","${row.value}"`)].join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `bazaarx-${key.value}.csv`; link.click(); URL.revokeObjectURL(link.href);
    feedback.value = "Your CSV report has been downloaded.";
  } else if (key.value === "settings") {
    update(rows.value[0]);
  } else {
    rows.value.unshift({ name: `NEW-${Date.now().toString().slice(-5)}`, detail: `Created in ${page.value.title.toLowerCase()} demo`, status: "Draft", value: "Just created" });
    localStorage.setItem(`bx-admin-${key.value}`, JSON.stringify(rows.value));
    feedback.value = `${page.value.title} draft created.`;
  }
}
</script>

<template><section class="admin-tools"><div class="admin-tools-heading"><div><span>{{ page.label }}</span><h1>{{ page.title }}</h1><p>{{ page.description }}</p></div><button @click="primaryAction"><ArrowDownToLine v-if="['analytics','audit-logs','users'].includes(key)" /><Plus v-else />{{ page.action }}</button></div><div class="admin-tool-stats"><article v-for="(stat,index) in page.stats" :key="stat"><small>{{ ["Platform total","Current period","Needs attention"][index] }}</small><b>{{ stat }}</b><span><Activity /> Updated just now</span></article></div><div class="admin-tool-panel"><header><div><h2>{{ key === 'fraud' ? 'Risk alerts' : key === 'support' ? 'Ticket queue' : key === 'shipments' ? 'Shipment overview' : 'Records' }}</h2><small>{{ filtered.length }} records in this view</small></div><label><Search /><input v-model="search" aria-label="Search admin records" placeholder="Search records" /></label></header><div v-if="['analytics','fraud'].includes(key)" class="admin-chart" :aria-label="key === 'fraud' ? 'Risk trend chart' : 'Marketplace GMV chart'"><span v-for="n in [34,48,43,65,53,76,62,85,70,96,81,100]" :key="n" :style="{height:`${n}%`}"></span></div><table><thead><tr><th>Reference</th><th>Details</th><th>Status</th><th>Value</th><th>Action</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.name"><td><b>{{ row.name }}</b></td><td>{{ row.detail }}</td><td><span class="admin-tool-badge" :class="{ risk: /risk|urgent|delayed/i.test(row.status) }">{{ row.status }}</span></td><td>{{ row.value }}</td><td><button class="row-button" @click="update(row)">{{ ['returns','fraud'].includes(key) ? 'Review' : key === 'support' ? 'Assign' : 'Update' }} <ChevronRight /></button></td></tr></tbody></table><div v-if="!filtered.length" class="tool-no-results"><ShieldAlert /><b>No matching records</b><span>Try changing your search.</span></div><p v-if="feedback" class="admin-feedback" role="status"><CheckCircle2 />{{ feedback }}</p></div></section></template>

<style scoped>
.admin-tools{color:#182940}.admin-tools-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 19px}.admin-tools-heading>div>span{font-size:9px;font-weight:800;letter-spacing:1px;color:#e95325}.admin-tools-heading h1{font:800 25px Manrope;margin:6px 0}.admin-tools-heading p{font-size:11px;color:#778599;margin:0}.admin-tools-heading button{border:0;border-radius:8px;padding:11px 13px;background:#f4511e;color:white;font-weight:700;display:flex;align-items:center;gap:7px;cursor:pointer}.admin-tools-heading button svg{width:15px}.admin-tool-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-bottom:14px}.admin-tool-stats article,.admin-tool-panel{background:white;border:1px solid #e7ecf2;border-radius:11px;padding:15px;box-shadow:0 8px 20px #19304a08}.admin-tool-stats article{display:grid;gap:8px}.admin-tool-stats small{color:#8490a0;font-size:10px}.admin-tool-stats b{font-size:17px}.admin-tool-stats span{display:flex;align-items:center;gap:5px;color:#138552;font-size:9px}.admin-tool-stats svg{width:13px}.admin-tool-panel>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.admin-tool-panel h2{font-size:15px;margin:0 0 4px}.admin-tool-panel header small{font-size:10px;color:#8994a3}.admin-tool-panel header label{display:flex;align-items:center;gap:7px;border:1px solid #dfe5ec;border-radius:7px;padding:8px;color:#7f8c9c}.admin-tool-panel header label svg{width:14px}.admin-tool-panel input{border:0;outline:0;font:inherit;font-size:11px;min-width:130px}.admin-tool-panel table{width:100%;border-collapse:collapse;font-size:10px}.admin-tool-panel th,.admin-tool-panel td{text-align:left;border-top:1px solid #edf0f4;padding:11px 7px}.admin-tool-panel th{color:#7c8999}.admin-tool-panel td{color:#506078}.admin-tool-panel td b{color:#203048}.admin-tool-badge{display:inline-block;border-radius:20px;background:#ebf8f1;color:#178351;padding:5px 8px;font-size:9px}.admin-tool-badge.risk{background:#fff0e9;color:#c94a24}.row-button{display:flex;align-items:center;gap:3px;border:1px solid #e0e6ed;border-radius:6px;background:white;padding:5px 7px;color:#31547c;font-size:10px;cursor:pointer}.row-button svg{width:12px}.admin-chart{height:100px;margin:8px 0 14px;display:flex;align-items:flex-end;gap:8px;border-bottom:1px solid #e5eaf0}.admin-chart span{flex:1;background:linear-gradient(#63a4ff,#2463ce);border-radius:4px 4px 0 0}.tool-no-results{display:grid;justify-items:center;gap:6px;padding:25px;color:#8290a1;font-size:11px}.tool-no-results svg{color:#f4511e}.admin-feedback{display:flex;align-items:center;gap:7px;color:#138552;font-size:11px}.admin-feedback svg{width:15px}@media(max-width:680px){.admin-tools-heading{align-items:flex-start;flex-direction:column}.admin-tool-stats{grid-template-columns:1fr}.admin-tool-panel{overflow:auto}.admin-tool-panel table{min-width:620px}.admin-tool-panel>header{align-items:flex-start;gap:9px;flex-direction:column}}
</style>
