<script setup lang="ts">
import { computed, ref } from "vue";
import { LifeBuoy, Search, MessageCircle, ChevronDown, CheckCircle2 } from "lucide-vue-next";
import SiteHeader from "../components/SiteHeader.vue";
import SiteFooter from "../components/SiteFooter.vue";

interface Ticket { id: string; topic: string; message: string; createdAt: string; status: string }
const query = ref("");
const topic = ref("Order and delivery");
const message = ref("");
const submitted = ref(false);
const faqs = [
  { q: "How can I track my order?", a: "Open My Account → My orders, then choose Track order to see the latest delivery step." },
  { q: "How do I request a return?", a: "Open Returns & refunds, select the order and item, then send the reason to start a request." },
  { q: "Which payment methods are available?", a: "This demo supports cash on delivery and a simulated card payment. No real payment is taken." },
  { q: "How do I contact a seller?", a: "Open Buyer–Seller chat and choose a store to start a conversation." },
];
const filteredFaqs = computed(() => faqs.filter((item) => `${item.q} ${item.a}`.toLowerCase().includes(query.value.toLowerCase())));
const tickets = ref<Ticket[]>(JSON.parse(localStorage.getItem("bx-support-tickets") ?? "[]") as Ticket[]);
function submit() { if (!message.value.trim()) return; tickets.value.unshift({ id: `BX-${Date.now().toString().slice(-6)}`, topic: topic.value, message: message.value.trim(), createdAt: new Date().toISOString(), status: "Open" }); localStorage.setItem("bx-support-tickets", JSON.stringify(tickets.value)); message.value = ""; submitted.value = true; }
</script>

<template><div class="page-shell"><SiteHeader /><main class="container content-page"><div class="breadcrumb"><RouterLink to="/">Home</RouterLink><span>/</span><span>Support center</span></div><div class="support-intro"><span class="support-mark"><LifeBuoy /></span><span class="eyebrow">WE’RE HERE TO HELP</span><h1>How can we help?</h1><p>Search common questions or send our support team a message.</p><label><Search /><input v-model="query" aria-label="Search help topics" placeholder="Search orders, returns, payments..." /></label></div><div class="support-grid"><section class="support-panel"><h2>Popular questions</h2><details v-for="faq in filteredFaqs" :key="faq.q"><summary>{{ faq.q }}<ChevronDown /></summary><p>{{ faq.a }}</p></details><p v-if="!filteredFaqs.length" class="no-results">No matching help topics. Send us a support request.</p></section><form class="support-panel ticket-form" @submit.prevent="submit"><div class="panel-title"><MessageCircle /><div><h2>Contact support</h2><p>We usually reply within one business day.</p></div></div><label>What do you need help with?<select v-model="topic"><option>Order and delivery</option><option>Returns and refunds</option><option>Payments</option><option>Account access</option><option>Other</option></select></label><label>Your message<textarea v-model="message" rows="4" placeholder="Share the details that will help us resolve this."></textarea></label><button class="support-button" type="submit">Send message</button><p v-if="submitted" class="success"><CheckCircle2 /> Your support request has been saved.</p><div v-if="tickets.length" class="ticket-history"><b>Recent requests</b><p v-for="ticket in tickets.slice(0,3)" :key="ticket.id">{{ ticket.id }} · {{ ticket.topic }} <span>{{ ticket.status }}</span></p></div></form></div></main><SiteFooter /></div></template>

<style scoped>
.support-intro{text-align:center;padding:20px 0 28px}.support-mark{margin:auto auto 13px;width:46px;height:46px;display:grid;place-items:center;border-radius:14px;background:#fff0e9;color:#f4511e}.support-intro h1{font-size:31px;color:#14243c;margin:8px}.support-intro p{color:#738198;margin:0 0 18px}.support-intro label{margin:auto;max-width:540px;display:flex;align-items:center;gap:9px;background:white;border:1px solid #e1e7ef;border-radius:10px;padding:0 13px;height:46px;color:#718098}.support-intro input{border:0;outline:0;flex:1;min-width:0;font:inherit}.support-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:18px}.support-panel{background:white;border:1px solid #e8edf3;border-radius:14px;padding:22px;box-shadow:0 10px 28px #2135500a}.support-panel h2{margin:0 0 13px;color:#1d2c43;font-size:18px}.support-panel details{border-top:1px solid #edf0f4;padding:15px 0}.support-panel summary{list-style:none;display:flex;justify-content:space-between;gap:8px;cursor:pointer;font-weight:700;font-size:13px;color:#25354c}.support-panel summary::-webkit-details-marker{display:none}.support-panel summary svg{width:17px;color:#79869a;flex:none}.support-panel details[open] summary svg{transform:rotate(180deg)}.support-panel details p,.no-results{font-size:12px;line-height:1.6;color:#6d7b90;margin:10px 0 0}.panel-title{display:flex;align-items:center;gap:12px;margin-bottom:12px}.panel-title>svg{color:#f4511e}.panel-title p{margin:0;color:#7c899b;font-size:12px}.ticket-form label{display:grid;gap:7px;margin:13px 0;color:#304057;font-size:12px;font-weight:700}.ticket-form select,.ticket-form textarea{border:1px solid #dfe5ec;border-radius:8px;padding:11px;font:inherit;font-weight:400;color:#304057;background:white}.support-button{background:#f4511e;border:0;color:white;border-radius:8px;padding:11px 15px;font-weight:700;cursor:pointer}.success{display:flex;align-items:center;gap:6px;color:#188859;font-size:12px}.success svg{width:16px}.ticket-history{margin-top:18px;border-top:1px solid #edf0f4;padding-top:14px;font-size:12px;color:#34445b}.ticket-history p{display:flex;justify-content:space-between;color:#6c7a8d}.ticket-history span{color:#178557}@media(max-width:760px){.support-grid{grid-template-columns:1fr}.support-intro h1{font-size:26px}}
</style>
